### PR TITLE
Create CODEOWNERS

### PR DESCRIPTION
**Pull request by ssbarnea**
See: https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners

### CODE REVIEW

**Comment by ssbarnea** [comment]
@konstruktoid Apparently your repository is failing on the eco pipeline. Did you manage to merge something into it that is not passing the linting by accident?

**Comment by konstruktoid** [comment]
@ssbarnea, `yaml: line too long (161 > 160 characters) (line-length)` but that was fixed four days ago in my repo.

**Comment by ssbarnea** [comment]
Well that us when we seen it. How are you running the linter on pull requests? Asking only in order to assure that the change to get broken again would be very low.

**Comment by konstruktoid** [comment]
> How are you running the linter on pull requests?
https://github.com/konstruktoid/ansible-docker-rootless/blob/main/.github/workflows/main.yml

**Pull request merged**
