### PR TITLE
fix: improve git file discovery with untracked and removed files

### LINKED ISSUE #1647: ansible-lint tries to lint removed files not yet staged in git directory
##### Summary

When linting a git-enabled directory, if any file is removed from the directory but is not yet staged with `git add`, `ansible-lint` tries to lint it even though it does not exist anymore.

This is due to using `git ls-files` to detect files, as this command also returns deleted and not staged or commited files.

##### Issue Type

- Bug Report

##### Ansible and Ansible Lint details

```console (paste below)
$ ansible --version
ansible [core 2.11.2]
  config file = None
  configured module search path = ['~/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = ~/.pyenv/versions/3.9.1/envs/ansible-tests/lib/python3.9/site-packages/ansible
  ansible collection location = ~/.ansible/collections:/usr/share/ansible/collections
  executable location = ~/.pyenv/versions/ansible-tests/bin/ansible
  python version = 3.9.1 (default, Feb 21 2021, 17:37:26) [Clang 12.0.0 (clang-1200.0.31.1)]
  jinja version = 3.0.1
  libyaml = True

$ ansible-lint --version
ansible-lint 5.1.0a1 using ansible 2.11.2
```

- ansible installation method: pip
- ansible-lint installation method: pip

##### OS / ENVIRONMENT

Can be reproduced both in `ansible-lint` `5.0.12` and `5.1.0a1`.

##### STEPS TO REPRODUCE

```console (paste below)
$ ansible-galaxy collection init xabinapal.test
- Collection xabinapal.test was created successfully

$ cd xabinapal/test
$ mkdir -p roles/test/tasks
$ touch roles/test/tasks/main.yml

$ git init
$ git add -A
$ git commit -m "first commit"

$ ansible-lint
$ echo $?
0
```

```console (paste below)
$ rm roles/test/tasks/main.yml
$ git status
On branch master
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	deleted:    roles/test/tasks/main.yml

no changes added to commit (use "git add" and/or "git commit -a")

$ ansible-lint -v
INFO     Added ANSIBLE_COLLECTIONS_PATH=~/.cache/ansible-lint/b9d075/collections
INFO     Added ANSIBLE_ROLES_PATH=~/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:roles
INFO     Added ANSIBLE_COLLECTIONS_PATH=~/.cache/ansible-lint/b9d075/collections:~/.cache/ansible-lint/b9d075/collections
INFO     Added ANSIBLE_ROLES_PATH=~/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:roles:roles
INFO     Discovered files to lint using: git ls-files -z
INFO     Discovered files to lint using: git ls-files -z
WARNING  Listing 1 violation(s) that are fatal
load-failure: [Errno 2] No such file or directory: 'roles/test/tasks/main.yml' (filenotfounderror)
roles/test/tasks/main.yml:1

You can skip specific rules or tags by adding them to your configuration file:
# .ansible-lint
warn_list:  # or 'skip_list' to silence them completely
  - load-failure  # Failed to load or parse file

Finished with 1 failure(s), 0 warning(s) on 5 files.

$ git ls-files
README.md
galaxy.yml
plugins/README.md
roles/test/tasks/main.yml
```

```console (paste below)
$ git add roles/test/tasks/main.yml
$ git status 
On branch master
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	deleted:    roles/test/tasks/main.yml

$ ansible-lint
$ echo $?
0

$ git ls-files
README.md
galaxy.yml
plugins/README.md
```

##### Desired Behaviour

Removed files should not be taken into account even if they haven't been staged. I don't think `git ls-files` can list every file *except* removed ones in a simple way but, with `git ls-files -d`, the subset of removed files can be retrieved. Subtracting that list from the original one could be one way of fixing this. If this idea is approved, I could submit a PR.

```console (paste below)
$ git status
On branch master
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	deleted:    roles/test/tasks/main.yml

no changes added to commit (use "git add" and/or "git commit -a")

$ git ls-files
README.md
galaxy.yml
plugins/README.md
roles/test/tasks/main.yml

$ git ls-files -d
roles/test/tasks/main.yml
```

##### Actual Behaviour

`ansible-lint` tries to lint removed files. Actual behaviour has already been shown in this issue.

### PR DESCRIPTION
**Pull request by xabinapal**
Closes #1647.

Uses two distinct `git ls-files` commands to obtain a full list of lintable files, including those not yet added to staging area, both new files and removed files.

### CODE REVIEW

**Comment by ssbarnea** [comment]
I will need some extra feedback for this change from others as I have bit of mixed feelings.

For example, if someone is producing temp files that are untracked and they forgot to add the to gitignore, the linter will start looking at them. Believe me or not, I always encounter projects that forget to do so, usually they install collections/roles someone inside the git tree.

It could have being cool to have it a single command.

**Comment by xabinapal** [comment]
IMHO, no linter should have different behaviour depending on whether it is executed on a git-enabled repository or not. At most, `.gitignore` can be taken into account (if I don't want a file to be commited, why would I want to lint it?) but, except that, the subset of lintable files should be the same in both scenarios to avoid confusion between users.

Maybe I'm being too naive, but I expect that if somebody forgot to gitignore some paths, those paths will end up being commited and linted anyway, manually or in a CI pipeline.

What bothers me is that, when developing a complex collection with many files, I refactor them in a regular basis: changing filenames or creating new files to group related tasks in different ways. Having to `git add` those files every time is too error prone.

However, if this is finally not accepted, if you ask me, the removed files section should be considered no matter what.

**Comment by ssbarnea** [comment]
@xabinapal Focus on fixing the current broken checks. I am sure that one way or another we will merge this, I do find your change benefic. 

In fact the original reason why we started using git to identify the files is related to gitignore. We did not want to force people to maintain a two list of excludes, one for git and once for the linter. Parsing the .gitignore file is far from easy, so we ended up reusing git.  At that time some people complained about not supporting other VCS but the reality is that they are so few, that they can get away using the fallback find instead.

Shortly, I do support your change, I almost daily make a mistake related to that bug, but CI is reporting back.

**Review by webknjaz — APPROVED** [review]

**Comment by xabinapal** [comment]
Sorry to ask @ssbarnea but do I need to fix anything? I see all checks have passed after your merge. Also, I've just run them in my own fork without that merge commit and they are also passing, I don't know why they did fail before.

**Review by ssbarnea — APPROVED** [review]

**Comment by ssbarnea** [comment]
@xabinapal Thanks! I hope to see more fixed from you.

**Pull request merged**
