### PR TITLE
Enable using relative paths for option 'kinds' in config file.

### PR DESCRIPTION
**Pull request by dsoares**
See #1774.

### CODE REVIEW

**Review by webknjaz — CHANGES_REQUESTED** [review]
@dsoares thanks for your contribution! At the moment it seems incomplete:
- we need _a new test_ added that would cover the new code branch
- also, this seems to break the docs build (https://readthedocs.org/projects/ansible-lint/builds/15586393/) which means that it potentially introduces a regression, _could you look into it, please?_ I'll close+reopen this PR to retrigger the RTD build in case its flaky for some reason to make sure that it is indeed related to your change.

Meanwhile, I'll trigger a CI run: it doesn't start automatically for the first-time contributions and needs a maintainer approval but after any of your PRs is merged, this won't be necessary.

**Comment by webknjaz** [comment]
> * also, this seems to break the docs build ([readthedocs.org/projects/ansible-lint/builds/15586393](https://readthedocs.org/projects/ansible-lint/builds/15586393/)) which means that it potentially introduces a regression, _could you look into it, please?_ I'll close+reopen this PR to retrigger the RTD build in case its flaky for some reason to make sure that it is indeed related to your change.

UPD: another RTD build has failed for this PR — https://readthedocs.org/projects/ansible-lint/builds/15602553/. I've also manually triggered rebuilding the `main` branch HEAD and it succeeded (https://readthedocs.org/projects/ansible-lint/builds/15602560/) which proves that the problem is caused by the patch in this PR and needs to be fixed before we can merge it.

This is also visible in the CI: https://github.com/ansible-community/ansible-lint/runs/4607543398?check_suite_focus=true — it looks like about a half of the tests are failing with this change. This must be fixed for the PR to be acceptable.

**Comment by ssbarnea** [comment]
@dsoares Can you please address the current problems?

**Comment by ssbarnea** [comment]
@dsoares I am closing this PR due to lack of updates. If you can fix it I will be more than happy to review it.

**Pull request closed without merging**
