### PR TITLE
Ensure that yamllint config ignore entries are used

### LINKED ISSUE #1344: .yamllint file in root directory is not used when ansible-lint runs yamllint
##### Summary

See background: https://github.com/ansible-community/ansible-lint/discussions/1150#discussioncomment-367068

##### Issue Type

- Bug Report

##### Ansible and Ansible Lint details

Latest from pip.

##### OS / ENVIRONMENT

Ubuntu 20.04, GitHub Actions CI

##### STEPS TO REPRODUCE

TODO: I'll be posting this shortly.

##### Desired Behaviour

TODO.

##### Actual Behaviour

TODO.

### PR DESCRIPTION
**Pull request by felixfontein**
There are two problems why `ignore` entries were ignored:
1. The way `YamlLintConfig.extend()` works with `ignore` entries, it is important to use the extended config instead of the original one.
2. The path needs to be supplied to `run()` so that yamllint can process its `ignore` config entries.

Fixes: #1344

### CODE REVIEW

**Comment by felixfontein** [comment]
Well, the CI failure is an interesting one: the `.yamllint` file in the repo's root explicitly ignores one of the test files, and if ansible-lint uses `.yamllint` the ignore entries, this causes the test to not work correctly since `ansible-lint` no longer reports the `yamllint` problems in that file.

**Comment by felixfontein** [comment]
@ssbarnea finally the tests passed ;)

**Review by ssbarnea — APPROVED** [review]

**Comment by felixfontein** [comment]
@ssbarnea thanks for reviewing and merging!

**Comment by geerlingguy** [comment]
Thanks!

**Pull request merged**
