### PR TITLE
Address pylint missing-class-docstring (old)

### PR DESCRIPTION
**Pull request by ssbarnea**
Most of classes without a docstring were the rules and for these we
moved the description into the docstring.

This change needs extra attention regarding on how the documentation
is built, so we do not mess its rendering.

### CODE REVIEW

**Review by cidrblock — APPROVED** [review]

**Review by cognifloyd — COMMENTED** [review]
Can we wrap the long first lines of the doc strings more?

**Comment by cognifloyd** [comment]
I also wonder if we'll need to do `dedent(__doc__)` for some of these.

**Comment by cognifloyd** [comment]
Yes. Looks like the multiline doc strings need `dedent`. See the read the docs build: https://ansible-lint--1993.org.readthedocs.build/en/1993/default_rules.html#command-instead-of-module

**Comment by cidrblock** [comment]
thinking aloud, rather than `__doc__`, if these need to manipulated, would a @property in the base class call `description` work? (that returned __doc__ with extra lines removed etc if needed?)

**Comment by ssbarnea** [comment]
Main reason for attempt to use docstring was that pylint required it and we did not want to add yet another text. We might go for using shortdesc instead which is not supposed to be more than a line.

I am also considering using markdown but i do not yet know how to make sphinx read docstring as md.

**Comment by cognifloyd** [comment]
Markdown in doc strings: https://stackoverflow.com/questions/56062402/force-sphinx-to-interpret-markdown-in-python-docstrings-instead-of-restructuredt

**Comment by cognifloyd** [comment]
Instead of explicitly doing `description = __doc__`, what if we used a [classmethod property](https://stackoverflow.com/a/1800999/1134951) to return `cls.__doc__`? If someone overwrites the property with a `description` attribute, then that will naturally take precedence (ie, effectively how things are now).

**Pull request closed without merging**
